### ISSUE TITLE
Make Wireframe design on Balsamiq

### ISSUE THREAD

**Issue by DanielHunte** [maiandrew23/LockBox#15]
- [x] Create overall physical design
- [x] Implement menu options
- [x] Implement printing

**Comment by DanielHunte** [comment]
### Create overall physical design
Link to Balsamiq wireframe created (https://drive.google.com/file/d/1SXso_OQVTCXxKtyZkf9CWoW-62Kzah9R/view?usp=sharing)
Screenshot:
<img width="422" alt="lockbox" src="https://user-images.githubusercontent.com/60459423/110678762-a8b53680-81a4-11eb-893f-0efaa4e8dfa3.png">

**Comment by maiandrew23** [comment]
![image](https://user-images.githubusercontent.com/55074018/113166657-fad00180-9210-11eb-9b49-fbca3a61d646.png)

Menu items have been decided. The program will operate in a state machine with the following flow. * and # keys will be use to navigate through the item selections.

**Comment by maiandrew23** [comment]
![image](https://user-images.githubusercontent.com/55074018/113187276-a8014480-9226-11eb-8fab-9043d2867d66.png)

An UX simulation is created to simulate navigating through the menu.

**Comment by maiandrew23** [comment]
Implemented Receipt Layout for the following instances:
New Device Registered
![image](https://user-images.githubusercontent.com/55074018/113904101-af34cf00-979f-11eb-92cf-2cc7d66547ac.png)

Display Points
![image](https://user-images.githubusercontent.com/55074018/113904262-e4d9b800-979f-11eb-93b4-09e40ca9e438.png)

Checkout Device
![image](https://user-images.githubusercontent.com/55074018/113905649-5ebe7100-97a1-11eb-83b8-40fcd8aa07ac.png)

Admin Display All
![image](https://user-images.githubusercontent.com/55074018/113904457-1783b080-97a0-11eb-886f-2c04f432f9a0.png)
