### ISSUE TITLE
Create Wireframe for Browser Interface

### ISSUE THREAD

**Issue by maiandrew23** [maiandrew23/LockBox#19]
- [x] Create layout for main page "index.html"
- [x] Create layout for admin page "admin.html"
- [x] Create Layout for guest page "guest.html"
Design the web interface for the LockBox. The admin should be able to get on the website and access the controls of the LockBox as well as seeing a full list of registered devices on the box with the option of clearing them. Admin does not require log in at this time.

**Comment by maiandrew23** [comment]
Created wireframe for browser interface for admin and guest. Link is active on the lockbox Balsamiq page: 

https://drive.google.com/file/d/1SXso_OQVTCXxKtyZkf9CWoW-62Kzah9R/view

![image](https://user-images.githubusercontent.com/55074018/115160599-0de32e00-a067-11eb-853a-c6632e50a558.png)

**Comment by DanielHunte** [comment]
https://drive.google.com/file/d/1SXso_OQVTCXxKtyZkf9CWoW-62Kzah9R/view
