### ISSUE TITLE
Static assets (CSS etc) not loading in Flask UI

### ISSUE THREAD

**Issue by ffund** [maiandrew23/LockBox#21]
When running the Flask app, static assets such as CSS files are not returned by the server. Note the 404s in the example below:

```
192.168.12.1 - - [23/Apr/2021 09:38:19] "GET / HTTP/1.1" 200 -
192.168.12.1 - - [23/Apr/2021 09:38:19] "GET /assets/bootstrap/css/bootstrap.min.css HTTP/1.1" 404 -
192.168.12.1 - - [23/Apr/2021 09:38:19] "GET /assets/css/Header-Dark.css HTTP/1.1" 404 -
192.168.12.1 - - [23/Apr/2021 09:38:19] "GET /assets/css/Navigation-Clean.css HTTP/1.1" 404 -
192.168.12.1 - - [23/Apr/2021 09:38:19] "GET /assets/css/styles.css HTTP/1.1" 404 -
192.168.12.1 - - [23/Apr/2021 09:38:19] "GET /favicon.ico HTTP/1.1" 404 -
```

**Comment by ffund** [comment]
Try this directory structure:

* static HTML files are in `html`
* in `app.py`, set it up with `static_folder='html'` and then when sending static HTML files, just path their name, not `html/name`
* in HTML files, refer to static assets with path: `html/assets/...`

**Comment by ffund** [comment]
See e.g. this example:

![image](https://user-images.githubusercontent.com/2316553/115881762-14342a00-a41a-11eb-88fe-a4a52a54f1fc.png)

When testing, make sure to do a "hard refresh" (also refresh any cached items) after changing HTML or CSS - in Chrome, use Ctrl+Shift+R (Linux), Cmd+Shift+R (Mac), or Ctrl+F5 (Windows).

**Comment by ffund** [comment]
@maiandrew23 please see the comments above and https://github.com/maiandrew23/LockBox/commit/e37ca08b879603479cd2c94584404247bb92f759 as follow-up to our conversation on Wednesday.

**Comment by maiandrew23** [comment]
This works now. Thank you!
