### ISSUE TITLE
Testing Printer Subsystem

### ISSUE THREAD

**Issue by maiandrew23** [maiandrew23/LockBox#5]
- [x] To ensure the serial port is operation, perform a UART Loopback test on the Raspberry Pi, making the necessary wire connections between the Pi and printer.
- [x] Print diagnostic receipt.
- [x] Install relevant library and test printing different things
- [x] Update code in lockbox.py and demo.py

**Comment by DanielHunte** [comment]
### Perform a UART Loopback test on the Raspberry Pi to ensure the serial port is operation.

* Connect VH to 5V pin on pi and GND to ground on pi
* Connect RX to TX on pi and TX to RX on pi
* Use "sudo raspi-config" command to activate UART serial pins
* Send AT command through serial using serial library

Expected Result: Receive a "OK" response

**Comment by DanielHunte** [comment]
### Perform a UART Loopback test on the Raspberry Pi to ensure the serial port is operation.

The correct connections was made and the AT command was sent to the printer. No "OK" response was received but the printer printed "AT" instead. I then tried to print "Hello" which worked.
<img width="285" alt="ss2" src="https://user-images.githubusercontent.com/60459423/112360891-30bd3500-8ca9-11eb-8fb9-a93baecbd8c4.png">
![ss](https://user-images.githubusercontent.com/60459423/112360911-3450bc00-8ca9-11eb-9905-f954e21513f3.jpg)

**Comment by DanielHunte** [comment]
### Print diagnostic receipt

* Press the power button on the printer while connecting the printer to power.

Expected result: A diagnostic receipt should be printed

**Comment by DanielHunte** [comment]
> ### Print diagnostic receipt
> * Press the power button on the printer while connecting the printer to power.
> 
> Expected result: A diagnostic receipt should be printed

When I do this the printer does not turn on (the led does not blink) and nothing is printed. I believe this is a power issue. Maybe not enough current is being supplied to the printer.

**Comment by DanielHunte** [comment]
> > ### Print diagnostic receipt
> > 
> > * Press the power button on the printer while connecting the printer to power.
> > 
> > Expected result: A diagnostic receipt should be printed
> 
> When I do this the printer does not turn on (the led does not blink) and nothing is printed. I believe this is a power issue. Maybe not enough current is being supplied to the printer.

I tried this with a 5V 4A power supply directly connected to the printer and it still didn't work. After playing around with the printer I found out the correct way to print out the diagnostic sheet. At any point after the printer has turned on, hold down the button on the circuit board and the diagnostic sheet will print. The instructions supplied on Adafruit's site(https://learn.adafruit.com/mini-thermal-receipt-printer/first-test) were wrong.
![a1](https://user-images.githubusercontent.com/60459423/112367249-15095d00-8cb0-11eb-9afc-a083e40c22b1.jpg)
![a2](https://user-images.githubusercontent.com/60459423/112367267-19357a80-8cb0-11eb-94d4-497de496c127.jpg)

**Comment by DanielHunte** [comment]
> > ### Print diagnostic receipt
> > 
> > * Press the power button on the printer while connecting the printer to power.
> > 
> > Expected result: A diagnostic receipt should be printed
> 
> When I do this the printer does not turn on (the led does not blink) and nothing is printed. I believe this is a power issue. Maybe not enough current is being supplied to the printer.

I connect the printer to the pi. With the pi on, only the first line of the diagnostic sheet prints. With the pi off, the first line is printed and the second line is printed very faintly. This confirms that the 5V 2A power supply does not supply enough current to the printer. Therefore the 5V 4A power supply will be used from now on. 
![c](https://user-images.githubusercontent.com/60459423/112369499-9feb5700-8cb2-11eb-9828-dc859fe3dddb.jpg)

**Comment by DanielHunte** [comment]
### Install relevant library and test printing different things

* Follow instructions from https://github.com/adafruit/Python-Thermal-Printer and install the relevant libraries.
* Run printertest.py 

Expected result: A receipt should be printed testing all the different font sizes, justifications, barcodes and images.

**Comment by DanielHunte** [comment]
> ### Install relevant library and test printing different things
> * Follow instructions from https://github.com/adafruit/Python-Thermal-Printer and install the relevant libraries.
> * Run printertest.py
> 
> Expected result: A receipt should be printed testing all the different font sizes, justifications, barcodes and images.

The 5V 4A power supply was used to power both the pi and the printer. A 2.1mm DC barrel jack was used to connect the power supply to the breadboard.

The instructions in the README.md were followed and printertest.py was run using python3 (NOTE: only works with python3 not python2).
![last](https://user-images.githubusercontent.com/60459423/112372668-759b9880-8cb6-11eb-9773-b3efa9f04d6e.jpg)
