### ISSUE TITLE
Testing Solenoid Subsystem

### ISSUE THREAD

**Issue by maiandrew23** [maiandrew23/LockBox#6]
- [ ] Set up the amplifier circuit using the provided TIP transistor with heat sink installed.
  * Connect the output of the amplifier to the solenoid and apply Vcc to the amplifier circuit.
  * Ensure the solenoid is operation in both ends
 - [ ] Ensure that the throw length is sufficient to reach the locking mechanism on the box chassis. Repeat a couple times to ensure it it is fully operational.

**Comment by maiandrew23** [comment]
<h1>Solenoid Testing </h1>

- [x] Set up Solenoid and driver circuit:
- [x] Write solenoid setup and operation functions
- [x] Update demo.py to test the solenoid

## Setting up driver circuit

1. Connect a 1.2k ohm resistor on the base of the TIP104 transistor.
2. Connect the transistor emitter to GND.
3. Connect one end of the solenoid to the collector and the other end to a 5v power supply.
4. Connect a diode in parallel with the solenoid with the anode (+) on the collector. 
5. Connect the other end of resistor to GPIO 16

## GPIO Setup
For the setup function, setup GPIO16 as an output. Write methods in the Solenoid class to extend and contract the solenoid.

## Testing Solenoid 
In demo.py, write a test script that will extend and contract the solenoid 5 times with 3 second pauses between contraction and extension. Make sure the circuit does not overhead during this process.

Expected Result: Solenoid should extend and contract instantly without any mechanical jams. The transistor and the Pi should not be hot to the touch after the test.

**Comment by maiandrew23** [comment]
![image](https://user-images.githubusercontent.com/55074018/112358295-9956e280-8ca6-11eb-8102-2d140c383e55.png)

The solenoid circuit is set up on the bread board. The 1.2 ohm resistors are in between GPIO and the base of the transistor.
An LED is used to act as a diode, which is place in parallel with the solenoid.

**Comment by maiandrew23** [comment]
![image](https://user-images.githubusercontent.com/55074018/112359743-f8692700-8ca7-11eb-8b84-75bf1dc7a264.png)
lockbox.py
![image](https://user-images.githubusercontent.com/55074018/112359828-0dde5100-8ca8-11eb-92d0-fc4009a39117.png)
demo.py
The GPIO setup was written in lockbox.py which will write a HIGH for open and a LOW for closed.

**Comment by maiandrew23** [comment]
The circuit did not work properly as expected. After troubleshooting, it was discovered that the solenoid was only drawing about 400 mA. 
![image](https://user-images.githubusercontent.com/55074018/112360216-73cad880-8ca8-11eb-9df7-b29f67c2756e.png)
To try the circuit without the transistor circuit, only 600 mA was measured. The minimum required current is 800 mA. 

Since its possible that there is not enough current provided out of the 5v pin on the pi, a different power source was used. 
![image](https://user-images.githubusercontent.com/55074018/112360344-952bc480-8ca8-11eb-8d5e-8b6f23395f8e.png)
In this setup, the solenoid is directly connected across a power adapter used for an IPAD with a rating of 5.2V 2.4A. The current did not get any higher. 

To increase the current as much as possible, the multimeter and jumper cables were removed so the power supply can be directly connected to the solenoid as shown.
![image](https://user-images.githubusercontent.com/55074018/112360626-e3d95e80-8ca8-11eb-9b19-907562e7a63f.png)
In this setup, the solenoid had just enough force to activate. It was noticed that the usb and pi wires were very thin and could be the cause of the low current.

**Comment by DanielHunte** [comment]
> ![image](https://user-images.githubusercontent.com/55074018/112358295-9956e280-8ca6-11eb-8102-2d140c383e55.png)
> 
> The solenoid circuit is set up on the bread board. The 1.2 ohm resistors are in between GPIO and the base of the transistor.
> An LED is used to act as a diode, which is place in parallel with the solenoid.

Powering the solenoid with a 5V 4A supply, measured the voltage across the solenoid with the transistor connected and got 3.6V. This means the voltage across the transistor is 1.4V. The solenoid needs to be provided with at lease 5V to operate properly. We've determined that current is no longer an issue (using 4A supply) but voltage is. Therefore we will test the solenoid with a 9V boost converter.

**Comment by DanielHunte** [comment]
### Boost Converter Test
Well will use a 9V Step-Up Voltage Regulator U3V12F9:
<img width="212" alt="123" src="https://user-images.githubusercontent.com/60459423/116133065-48b71880-a69c-11eb-8039-f2b8e46548c4.png">


* Connect 5V power supply pin to Vin on the boost converter
* Connect power supply GND pin to GND on the boost converter.
* Measure the voltage across Vout on the boost converter and GND

Expected Result: Measure 9V on the multimeter

**Comment by DanielHunte** [comment]
> ### Boost Converter Test
> Well will use a 9V Step-Up Voltage Regulator U3V12F9:
> <img alt="123" width="212" src="https://user-images.githubusercontent.com/60459423/116133065-48b71880-a69c-11eb-8039-f2b8e46548c4.png">
> 
> * Connect 5V power supply pin to Vin on the boost converter
> * Connect power supply GND pin to GND on the boost converter.
> * Measure the voltage across Vout on the boost converter and GND
> 
> Expected Result: Measure 9V on the multimeter

The mentioned connections were made and 9.09V was measured across the boost converter.:
![boost](https://user-images.githubusercontent.com/60459423/116136405-422aa000-a6a0-11eb-8e82-a607c9f22b1d.jpg)

**Comment by DanielHunte** [comment]
### Test solenoid with transistor

* Connect one end of the solenoid to Vout on the boost converter
* Connect the other end of the solenoid to the collector of the transistor
* Connect the emitter of the transistor to GND
* Connect the base of the transistor to the one end of a 1k resistor
* Connect the other end of the resistor to GPIO16 on the pi
* Connect a diode across the solenoid is the opposite polarity
* Run demo.py and observe the solenoid

Expected result: The solenoid opens and closes at the specified times in demo.py

![connections](https://user-images.githubusercontent.com/60459423/116136562-743c0200-a6a0-11eb-8850-cc41e8171199.jpeg)

**Comment by DanielHunte** [comment]
> ### Test solenoid with transistor
> * Connect one end of the solenoid to Vout on the boost converter
> * Connect the other end of the solenoid to the collector of the transistor
> * Connect the emitter of the transistor to GND
> * Connect the base of the transistor to the one end of a 1k resistor
> * Connect the other end of the resistor to GPIO16 on the pi
> * Connect a diode across the solenoid is the opposite polarity
> * Run demo.py and observe the solenoid
> 
> Expected result: The solenoid opens and closes at the specified times in demo.py
> 
> ![connections](https://user-images.githubusercontent.com/60459423/116136562-743c0200-a6a0-11eb-8850-cc41e8171199.jpeg)

The mentioned connections were made and the solenoid open and closed as expected.
<img width="317" alt="demo" src="https://user-images.githubusercontent.com/60459423/116136699-a3eb0a00-a6a0-11eb-9005-fdd1041d7c91.png">
![final](https://user-images.githubusercontent.com/60459423/116136750-b8c79d80-a6a0-11eb-93b2-64885fdbf873.jpg)
