### ISSUE TITLE
Testing Character LCD

### ISSUE THREAD

**Issue by DanielHunte** [maiandrew23/LockBox#8]
- [x] Test if it turns on
- [x] Test backlight levels and set to a reasonable contrast
- [x] Try setup commands and see if a correct response is received
- [x] Write to both lines of the display
- [x] Make sure response time is virtually zero

**Comment by ffund** [comment]
### Test if it turns on 

Connect:

* Pin 1 (VSS) and pin 16 (BL- or K) are connected to the ground rail.
* Pin 2 (VDD) is connected to the 5V power rail.
* Pin 16 (BL+/A) is connected to the 5V power rail through a 220Ω series resistor.

Then, connect a GND pin from Pi to the GND rail, and a 5V pin from Pi to the 5V power rail. 

Expected result: nothing, until you have adjusted contrast.

**Comment by ffund** [comment]
### Test contrast

Instructions: Turn the knob on the potentiometer to a middle position, to start. Connect
the outside pins of the potentiometer to the ground rail and 5V power rail, respectively. (It doesn’t matter
which of the two outside pins is at GND and which is at 5V - the trimpot is symmetric.) The middle pin of
the potentiometer is connected to LCD pin 3 (V0).

Carefully turn the knob on the trimpot until you see a row of white squares appear on your LCD display.

Expected result: 
![2021-03-10_12-42](https://user-images.githubusercontent.com/2316553/110672897-23c71e80-819e-11eb-9a54-e109331424d4.png)

**Comment by ffund** [comment]
### Try setup commands

Implement init, on, and off functions in library.

Test by running demo.py

Expected result: when the on function runs, the display turns on; when the off function runs, the display turns off.

**Comment by maiandrew23** [comment]
> ### Test if it turns on
> Connect:
> 
> * Pin 1 (VSS) and pin 16 (BL- or K) are connected to the ground rail.
> * Pin 2 (VDD) is connected to the 5V power rail.
> * Pin 16 (BL+/A) is connected to the 5V power rail through a 220Ω series resistor.
> 
> Then, connect a GND pin from Pi to the GND rail, and a 5V pin from Pi to the 5V power rail.
> 
> Expected result: nothing, until you have adjusted contrast.

The LCD was wired accordingly and the display turns on as expected. 
![image](https://user-images.githubusercontent.com/55074018/110676764-56731600-81a2-11eb-8cb3-1b3022b2218c.png)

**Comment by maiandrew23** [comment]
> ### Test contrast
> Instructions: Turn the knob on the potentiometer to a middle position, to start. Connect
> the outside pins of the potentiometer to the ground rail and 5V power rail, respectively. (It doesn’t matter
> which of the two outside pins is at GND and which is at 5V - the trimpot is symmetric.) The middle pin of
> the potentiometer is connected to LCD pin 3 (V0).
> 
> Carefully turn the knob on the trimpot until you see a row of white squares appear on your LCD display.
> 
> Expected result:
> ![2021-03-10_12-42](https://user-images.githubusercontent.com/2316553/110672897-23c71e80-819e-11eb-9a54-e109331424d4.png)

The potentiometer is connected to 5V, V0, and GND respectively. Bright squares were visible after turning the knob approximately 85% of the way.
![image](https://user-images.githubusercontent.com/55074018/110677274-fc268500-81a2-11eb-85bd-cadae251c7af.png)

**Comment by maiandrew23** [comment]
> ### Try setup commands
> Implement init, on, and off functions in library.
> 
> Test by running demo.py
> 
> Expected result: when the on function runs, the display turns on; when the off function runs, the display turns off.

The init function was implemented Pins RS, E, and D4-D7 were set to GPIO.OUT.
A couple initial commands were sent to the LCD using write_arr_4bit function. 
![image](https://user-images.githubusercontent.com/55074018/111517191-2e982b00-872b-11eb-9245-f5e4d75dc3fa.png)

When the display off function was called, the display was successfully turn off:
![image](https://user-images.githubusercontent.com/55074018/111538766-77f47480-8743-11eb-82ae-7ef86c0aaf43.png)

After running demo.py which initializes the display class and calls showText to display "Test1" on the LCD and finally printing "Display setup finished". 
Running demo.py was successful:
![image](https://user-images.githubusercontent.com/55074018/111517487-80d94c00-872b-11eb-8852-69ca2d1cc698.png)
After running demo.py, "test1" is displayed on the LCD
![image](https://user-images.githubusercontent.com/55074018/111537025-58f4e300-8741-11eb-89dc-2007a115f4ac.png)
